version: "3.9"

services:
  api:
    container_name: pdf_convertor_python
    image: pdf_convertor_python
    build:
      dockerfile: "docker/api/Dockerfile"
    ports:
      - "7777:7777"
    restart: always

  soffice:
    container_name: soffice_container
    image: libreoffice/online
    ports:
      - "9980:9980"
    restart: always

