version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: tfsp
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: pdf_placeholder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data

  api:
    container_name: pdf_convertor_python
    image: pdf_convertor_python
    build:
      context: ./
      dockerfile: "docker/api/Dockerfile"
    volumes:
      - ./files:/files
    ports:
      - "443:7777"
    restart: always
    environment:
      DB_HOST: postgres
      DB_NAME: pdf_placeholder
      DB_USER: tfsp
      DB_PASS: 12345
      DB_PORT: "5432"

volumes:
  postgres_data:
