version: "3.9"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data


  api:
    container_name: pdf_convertor_python
    build:
      context: /root/PDF_placeholder/docker/api
      dockerfile: Dockerfile
    image: pdf_convertor_python
    volumes:
      - ./files:/files
    ports:
      - "7777:7777"
    restart: always

