version: "3.9"

services:
  api:
    container_name: pdf_convertor_python
    image: pdf_convertor_python
    build:
      dockerfile: "docker_/api/Dockerfile"
    volumes:
      - ./files:/files
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /bin/sh:/bin/sh:docker
    ports:
      - "7777:7777"
    restart: always

