"""update trans

Revision ID: 3e6d2176c571
Revises: 304623b9bd79
Create Date: 2023-12-23 06:14:43.887631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6d2176c571'
down_revision: Union[str, None] = '304623b9bd79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'file',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'file',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
