"""debit

Revision ID: 970801bfdbe9
Revises: 2ae7ebb339cf
Create Date: 2023-11-28 18:26:33.095230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970801bfdbe9'
down_revision: Union[str, None] = '2ae7ebb339cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('unlimited', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'unlimited')
    # ### end Alembic commands ###
