"""telegram

Revision ID: a8c9cfd8ad75
Revises: 3e6d2176c571
Create Date: 2024-01-06 06:38:21.407353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c9cfd8ad75'
down_revision: Union[str, None] = '3e6d2176c571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telegramID', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'telegramID')
    # ### end Alembic commands ###
