"""test 2

Revision ID: b4b14cf0a5b8
Revises: 0a82e033dc50
Create Date: 2023-11-28 01:31:06.996004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b14cf0a5b8'
down_revision: Union[str, None] = '0a82e033dc50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docx_file', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docx_file', 'deleted')
    # ### end Alembic commands ###
