"""models modification

Revision ID: de3945ccf518
Revises: b4b14cf0a5b8
Create Date: 2023-11-28 01:38:10.775700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de3945ccf518'
down_revision: Union[str, None] = 'b4b14cf0a5b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('unlimited', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'unlimited')
    # ### end Alembic commands ###
